// src/lib/consoleOrder.ts
export const CONSOLE_ORDER: string[] = [
  "Atari 2600",
  "NES",
  "Sega Master System",
  "Sega Genesis",
  "SNES",
  "Game Boy",
  "Sega Saturn",
  "PlayStation",
  "Nintendo 64",
  "Game Boy Color",
  "Dreamcast",
  "PlayStation 2",
  "Xbox",
  "GameCube",
  "Game Boy Advance",
  "Xbox 360",
  "PlayStation 3",
  "Nintendo Wii",
  "Nintendo DS",
  "PlayStation Portable",
  "Nintendo Wii U",
  "PlayStation 4",
  "Xbox One",
  "Nintendo Switch",
  "PlayStation 5",
  "Xbox Series X",
  "Nintendo Switch 2",
  "PC"
];
